version: '3.8'
services:
  education:
    image: mjkundta/education:${TAG}
    build:
      context: .
      dockerfile: ./apps/education/Dockerfile
      target: production
    command: node dist/apps/education/src/main
    restart: on-failure
    env_file: './apps/education/.env.production'
    mem_limit: 2g
    cpu_shares: 1024
