version: '3.8'
services:
  background:
    image: mjkundta/background:${TAG}
    build:
      context: .
      dockerfile: ./apps/background/Dockerfile
      target: production
    command: node dist/apps/background/src/main
    restart: on-failure
    env_file: './apps/background/.env.production'

  payment:
    image: mjkundta/payment:${TAG}
    build:
      context: .
      dockerfile: ./apps/payment/Dockerfile
      target: production
    command: node dist/apps/payment/src/main
    restart: on-failure
    env_file: './apps/payment/.env.production'
