version: '3.8'
services:
  gateway:
    image: mjkundta/gateway:${TAG}
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: production
    command: node dist/apps/gateway/src/main
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - NODE_ENV=production
  
  auth:
    image: mjkundta/auth:${TAG}
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: production
    command: node dist/apps/auth/src/main 
    restart: on-failure
    environment:
      - NODE_ENV=production

  user:
    image: mjkundta/user:${TAG}
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      target: production
    command: node dist/apps/user/src/main
    restart: on-failure
    environment:
      - NODE_ENV=production
  
  payment:
    image: mjkundta/payment:${TAG}
    build:
      context: .
      dockerfile: ./apps/payment/Dockerfile
      target: production
    command: node dist/apps/payment/src/main
    restart: on-failure
    environment:
      - NODE_ENV=production
  
  family:
    image: mjkundta/family:${TAG}
    build:
      context: .
      dockerfile: ./apps/family/Dockerfile
      target: production
    command: node dist/apps/family/src/main
    restart: on-failure
    environment:
      - NODE_ENV=production
    
  storage:
    image: mjkundta/storage:${TAG}
    build:
      context: .
      dockerfile: ./apps/storage/Dockerfile
      target: production
    command: node dist/apps/storage/src/main
    restart: on-failure
    environment:
      - NODE_ENV=production
  
  mailer:
    image: mjkundta/mailer:${TAG}
    build:
      context: .
      dockerfile: ./apps/mailer/Dockerfile
      target: production
    command: node dist/apps/mailer/src/main
    restart: on-failure
    environment:
      - NODE_ENV=production

  chat:
    image: mjkundta/chat:${TAG}
    build:
      context: .
      dockerfile: ./apps/chat/Dockerfile
      target: production
    command: node dist/apps/chat/src/main
    restart: on-failure
    environment:
      - NODE_ENV=production

  role:
    image: mjkundta/role:${TAG}
    build:
      context: .
      dockerfile: ./apps/role/Dockerfile
      target: production
    command: node dist/apps/role/src/main
    restart: on-failure
    environment:
      - NODE_ENV=production
  
  crawler:
    image: mjkundta/crawler:${TAG}
    build:
      context: .
      dockerfile: ./apps/crawler/Dockerfile
      target: production
    command: node dist/apps/crawler/src/main
    restart: on-failure
    environment:
      - NODE_ENV=production

  household:
    image: mjkundta/household:${TAG}
    build:
      context: .
      dockerfile: ./apps/household/Dockerfile
      target: production
    command: node dist/apps/household/src/main
    depends_on:
      - gateway
    restart: on-failure
    environment:
      - NODE_ENV=production