version: '3.8'
services:
  gateway:
    image: mjkundta/gateway:${TAG}
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: production
    command: node dist/apps/gateway/src/main
    ports:
      - '8080:8080'
    restart: on-failure
    env_file: './apps/gateway/.env.production'
    mem_limit: 2g
    cpu_shares: 1024

  auth:
    image: mjkundta/auth:${TAG}
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: production
    command: node dist/apps/auth/src/main
    restart: on-failure
    env_file: './apps/auth/.env.production'
    mem_limit: 2g
    cpu_shares: 1024
