version: '3.8'
services:
  calendar:
    image: mjkundta/calendar:${TAG}
    build:
      context: .
      dockerfile: ./apps/calendar/Dockerfile
      target: production
    command: node dist/apps/calendar/src/main
    restart: on-failure
    environment:
      - NODE_ENV=production
    mem_limit: 2g
    cpu_shares: 1024

  guideline:
    image: mjkundta/guideline:${TAG}
    build:
      context: .
      dockerfile: ./apps/guideline/Dockerfile
      target: production
    command: node dist/apps/guideline/src/main
    restart: on-failure
    environment:
      - NODE_ENV=production
    mem_limit: 2g
    cpu_shares: 1024
