version: '3.8'
services:
  storage:
    image: mjkundta/storage:${TAG}
    build:
      context: .
      dockerfile: ./apps/storage/Dockerfile
      target: production
    command: node dist/apps/storage/src/main
    restart: on-failure
    environment:
      - NODE_ENV=production
    mem_limit: 2g
    cpu_shares: 1024

  chat:
    image: mjkundta/chat:${TAG}
    build:
      context: .
      dockerfile: ./apps/chat/Dockerfile
      target: production
    command: node dist/apps/chat/src/main
    restart: on-failure
    environment:
      - NODE_ENV=production
    mem_limit: 2g
    cpu_shares: 1024
