version: '3.8'
services:
  storage:
    image: mjkundta/storage:${TAG}
    build:
      context: .
      dockerfile: ./apps/storage/Dockerfile
      target: production
    command: node dist/apps/storage/src/main
    restart: on-failure
    environment:
      - NODE_ENV=production

  mailer:
    image: mjkundta/mailer:${TAG}
    build:
      context: .
      dockerfile: ./apps/mailer/Dockerfile
      target: production
    command: node dist/apps/mailer/src/main
    restart: on-failure
    environment:
      - NODE_ENV=production

  chat:
    image: mjkundta/chat:${TAG}
    build:
      context: .
      dockerfile: ./apps/chat/Dockerfile
      target: production
    command: node dist/apps/chat/src/main
    restart: on-failure
    environment:
      - NODE_ENV=production
