version: '1.0'
services:
  gateway:
    image: mjkundta/gateway:latest
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: npm run start:dev gateway
    env_file:
      - ./apps/gateway/.env
    ports:
      - "8080:8080"
    depends_on:
      # - postgres1
      # - postgres2
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  
  auth:
    image: mjkundta/auth:latest
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    depends_on:
      - gateway
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  
  payment:
    image: mjkundta/payment:latest
    build:
      context: .
      dockerfile: ./apps/payment/Dockerfile
      target: development
    command: npm run start:dev payment
    env_file:
      - ./apps/payment/.env
    depends_on:
      - gateway
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  # postgres1:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-postgres}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
  #     PGDATA: /data/postgres
  #   restart: unless-stopped
  #   command: postgres -c listen_addresses='*'
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - postgres:/data/postgres
  
  # postgres2:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-postgres}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
  #     PGDATA: /data/postgres
  #   restart: unless-stopped
  #   command: postgres -c listen_addresses='*'
  #   ports:
  #     - '5433:5432'
  #   volumes:
  #     - postgres:/data/postgres
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   restart: unless-stopped
  #   volumes:
  #     - pgadmin:/root/.pgadmin

  rabbitmq:
    image: mjkundta/rabbitmq:latest
    ports:
      - '5672:5672'

# volumes:
#   postgres:
#   pgadmin: