version: '3.8'
services:
  finance:
    image: mjkundta/finance:${TAG}
    build:
      context: .
      dockerfile: ./apps/finance/Dockerfile
      target: production
    command: node dist/apps/finance/src/main
    restart: on-failure
    environment:
      - NODE_ENV=production