version: '3.8'
services:
  finance:
    image: mjkundta/finance:${TAG}
    build:
      context: .
      dockerfile: ./apps/finance/Dockerfile
      target: production
    command: node dist/apps/finance/src/main
    restart: on-failure
    env_file: './apps/finance/.env.production'

  shopping:
    image: mjkundta/shopping:${TAG}
    build:
      context: .
      dockerfile: ./apps/shopping/Dockerfile
      target: production
    command: node dist/apps/shopping/src/main
    restart: on-failure
    env_file: './apps/shopping/.env.production'
