version: '1.0'
services:
  gateway:
    image: mjkundta/gateway:latest
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: npm run start:dev gateway
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    restart: on-failure
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  
  auth:
    image: mjkundta/auth:latest
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    depends_on:
      - gateway
    restart: on-failure
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  
  payment:
    image: mjkundta/payment:latest
    build:
      context: .
      dockerfile: ./apps/payment/Dockerfile
      target: development
    command: npm run start:dev payment
    depends_on:
      - gateway
    restart: on-failure
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  
  sms:
    image: mjkundta/sms:latest
    build:
      context: .
      dockerfile: ./apps/sms/Dockerfile
      target: development
    command: npm run start:dev sms
    depends_on:
      - gateway
    restart: on-failure
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  family:
    image: mjkundta/family:latest
    build:
      context: .
      dockerfile: ./apps/family/Dockerfile
      target: development
    command: npm run start:dev family
    depends_on:
      - gateway
    restart: on-failure
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    
  storage:
    image: mjkundta/storage:latest
    build:
      context: .
      dockerfile: ./apps/storage/Dockerfile
      target: development
    command: npm run start:dev storage
    depends_on:
      - gateway
    restart: on-failure
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  rabbitmq:
    image: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure
    ports:
      - '5672:5672'