version: '3.8'
services:
  family:
    image: mjkundta/family:${TAG}
    build:
      context: .
      dockerfile: ./apps/family/Dockerfile
      target: production
    command: node dist/apps/family/src/main
    restart: on-failure
    env_file: './apps/family/.env.production'
