version: '1.0'
services:
  gateway:
    image: mjkundta/gateway:latest
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: node dist/apps/gateway/main
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    restart: on-failure
    environment:
      - NODE_ENV=production
  
  auth:
    image: mjkundta/auth:latest
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: node dist/apps/auth/main
    depends_on:
      - gateway
    restart: on-failure
    environment:
      - NODE_ENV=production
  
  payment:
    image: mjkundta/payment:latest
    build:
      context: .
      dockerfile: ./apps/payment/Dockerfile
      target: development
    command: node dist/apps/payment/main
    depends_on:
      - gateway
    restart: on-failure
    environment:
      - NODE_ENV=production
  
  sms:
    image: mjkundta/sms:latest
    build:
      context: .
      dockerfile: ./apps/sms/Dockerfile
      target: development
    command: node dist/apps/sms/main
    depends_on:
      - gateway
    restart: on-failure
    environment:
      - NODE_ENV=production

  rabbitmq:
    image: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure