apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      automountServiceAccountToken: false
      containers:
      - name: auth
        image: mjkundta/auth:<TAG>
        command: ["node", "dist/apps/auth/src/main"]
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        env:
        - name: NODE_ENV
          value: "production"