apiVersion: apps/v1
kind: Deployment
metadata:
  name: background-deployment
  labels:
    app: background
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: background
  template:
    metadata:
      labels:
        app: background
    spec:
      automountServiceAccountToken: false
      containers:
        - name: background
          image: mjkundta/background:latest
          imagePullPolicy: Always
          command: ['node', 'dist/apps/background/src/main.js']
          env:
            - name: NODE_ENV
              value: 'production'
---
apiVersion: v1
kind: Service
metadata:
  name: background
  labels:
    app: background
spec:
  selector:
    app: background
  ports:
    - protocol: TCP
      port: 8093
      targetPort: 8093
  type: ClusterIP
