apiVersion: v1
kind: Service
metadata:
  name: calendar
  labels:
    app: calendar
spec:
  selector:
    app: calendar
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP