apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
  labels:
    app: chat
spec:
  strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      automountServiceAccountToken: false
      containers:
        - name: chat
          image: mjkundta/chat:<TAG>
          command: ["node", "dist/apps/chat/src/main"]
          resources:
            limits:
              cpu: "0.25"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
          env:
            - name: NODE_ENV
              value: "production"
