apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-deployment
  labels:
    app: crawler
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      automountServiceAccountToken: false
      containers:
        - name: crawler
          image: mjkundta/crawler:<TAG>
          command: ["node", "dist/apps/crawler/src/main"]
          resources:
            limits:
              cpu: "0.25"
              memory: "512Mi"
          env:
            - name: NODE_ENV
              value: "production"

---
apiVersion: v1
kind: Service
metadata:
  name: crawler
  labels:
    app: crawler
spec:
  selector:
    app: crawler
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: ClusterIP

