apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
        env:
        - name: http.host
          value: "0.0.0.0"
        - name: transport.host
          value: "127.0.0.1"
        - name: xpack.security.enabled
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: ELASTIC_PASSWORD
          value: "Toan123456789"
        - name: xpack.security.transport.ssl.enabled
          value: "true"
        - name: xpack.license.self_generated.type
          value: "trial"
        - name: TZ
          value: "Asia/Ho_Chi_Minh"
        ports:
        - containerPort: 9200
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"