apiVersion: v1
kind: Service
metadata:
  name: family-service
  labels:
    app: family
spec:
  selector:
    app: family
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP
