apiVersion: apps/v1
kind: Deployment
metadata:
  name: family-deployment
  labels:
    app: family
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: family
  template:
    metadata:
      labels:
        app: family
    spec:
      automountServiceAccountToken: false
      containers:
        - name: family
          image: mjkundta/family:<TAG>
          command: ["node", "dist/apps/family/src/main"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          env:
            - name: NODE_ENV
              value: "production"
