apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      automountServiceAccountToken: false
      initContainers:
        - name: init-logs
          image: busybox
          command:
            [
              'sh',
              '-c',
              'if [ -d "/usr/src/app/logs" ]; then cp -R /usr/src/app/logs /usr/src/app/logs_backup; fi',
            ]
          volumeMounts:
            - name: log-volume
              mountPath: /usr/src/app/logs
      containers:
        - name: gateway
          image: mjkundta/gateway:<TAG>
          command: ['node', 'dist/apps/gateway/src/main.js']
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: '100m'
              memory: '512Mi'
          env:
            - name: NODE_ENV
              value: 'production'
            - name: REDIS_HOST
              value: 'redis'
            - name: REDIS_PORT
              value: '6379'
            - name: RABBIT_MQ_BACKGROUND_QUEUE
              value: 'BACKGROUND'
          volumeMounts:
            - name: log-volume
              mountPath: /usr/src/app/logs

        - name: filebeat
          image: docker.elastic.co/beats/filebeat-oss:7.15.0
          args: ['-c', '/usr/share/filebeat/filebeat.yml', '-e']
          volumeMounts:
            - name: config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
            - name: log-volume
              mountPath: /src/logs
          resources:
            limits:
              cpu: '50m'
              memory: '128Mi'
          securityContext:
            runAsUser: 0
      volumes:
        - name: config
          configMap:
            name: filebeat-config
        - name: log-volume
          persistentVolumeClaim:
            claimName: log-volume-claim
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    name: "gateway-filebeat"
    logging.metrics.enabled: false
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
    setup.ilm.enabled: false
    setup.template.enabled: false

    filebeat.inputs:
    - type: log
      scan_frequency: 1s
      enabled: true
      paths:
        - /src/logs/app.log
      fields:
        service: gateway
      fields_under_root: true
      json:
        keys_under_root: true
        message_key: 'message'
        overwrite_keys: true

    output.elasticsearch:
      hosts: ["https://elasticsearch.rancher.io.vn:443"]
      index: "famfund-app-production"
      username: "elastic"
      password: "Toan123456789"

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
