apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      automountServiceAccountToken: false
      containers:
      - name: gateway
        image: mjkundta/gateway:<TAG>
        command: ["node", "dist/apps/gateway/main"]
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        env:
        - name: NODE_ENV
          value: "production"
