apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      automountServiceAccountToken: false
      containers:
        - name: gateway
          image: mjkundta/gateway:<TAG>
          command: ["node", "dist/apps/gateway/src/main"]
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "400Mi"  
              cpu: "110m"     
            limits:
              memory: "800Mi" 
              cpu: "220m" 
          env:
            - name: NODE_ENV
              value: "production"
