apiVersion: apps/v1
kind: Deployment
metadata:
  name: household-deployment
  labels:
    app: household
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: household
  template:
    metadata:
      labels:
        app: household
    spec:
      automountServiceAccountToken: false
      containers:
        - name: household
          image: mjkundta/household:<TAG>
          command: ['node', 'dist/apps/household/src/main']
          resources:
            limits:
              cpu: '140m'
              memory: '512Mi'
          env:
            - name: NODE_ENV
              value: 'production'
---
apiVersion: v1
kind: Service
metadata:
  name: household
  labels:
    app: household
spec:
  selector:
    app: household
  ports:
    - protocol: TCP
      port: 8094
      targetPort: 8094
  type: ClusterIP
