apiVersion: apps/v1
kind: Deployment
metadata:
  name: household-deployment
  labels:
    app: household
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: household
  template:
    metadata:
      labels:
        app: household
    spec:
      automountServiceAccountToken: false
      containers:
        - name: household
          image: mjkundta/household:latest
          imagePullPolicy: Always
          command: ['node', 'dist/apps/household/src/main.js']
          env:
            - name: NODE_ENV
              value: 'production'
---
apiVersion: v1
kind: Service
metadata:
  name: household
  labels:
    app: household
spec:
  selector:
    app: household
  ports:
    - protocol: TCP
      port: 50004
      targetPort: 50004
  type: ClusterIP
