apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
  labels:
    app: logstash
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      automountServiceAccountToken: false
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.14.1
          env:
            - name: TZ
              value: "Asia/Ho_Chi_Minh"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Gi"
              cpu: "400m"