apiVersion: v1
kind: Service
metadata:
  name: mailer
  labels:
    app: mailer
spec:
  selector:
    app: mailer
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP
