apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer-deployment
  labels:
    app: mailer
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: mailer
  template:
    metadata:
      labels:
        app: mailer
    spec:
      automountServiceAccountToken: false
      containers:
        - name: mailer
          image: mjkundta/mailer:<TAG>
          command: ["node", "dist/apps/mailer/src/main"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: NODE_ENV
              value: "production"
