apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer-deployment
spec:
  strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: mailer
  template:
    metadata:
      labels:
        app: mailer
    spec:
      automountServiceAccountToken: false
      containers:
      - name: mailer
        image: mjkundta/mailer:<TAG>
        command: ["node", "dist/apps/mailer/src/main"]
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        env:
        - name: NODE_ENV
          value: "production"
