apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment-<TAG>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      automountServiceAccountToken: false
      containers:
      - name: payment
        image: mjkundta/payment:<TAG>
        command: ["node", "dist/apps/payment/main"]
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        env:
          - name: NODE_ENV
            value: "production"
