apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: payment
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      automountServiceAccountToken: false
      containers:
        - name: payment
          image: mjkundta/payment:<TAG>
          command: ["node", "dist/apps/payment/src/main"]
          resources:
            limits:
              cpu: "150m"
              memory: "512Mi"
          env:
            - name: NODE_ENV
              value: "production"

---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
