apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerjs-deployment
  labels:
    app: peerjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peerjs
  template:
    metadata:
      labels:
        app: peerjs
    spec:
      containers:
        - name: peerjs
          image: mjkundta/peerjs-server:latest
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: peerjs-service
spec:
  selector:
    app: peerjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: ClusterIP
