apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-deployment
spec:
  strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: sms
  template:
    metadata:
      labels:
        app: sms
    spec:
      automountServiceAccountToken: false
      containers:
      - name: sms
        image: mjkundta/sms:<TAG>
        command: ["node", "dist/apps/sms/main"]
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        env:
        - name: NODE_ENV
          value: "production"
