apiVersion: v1
kind: Service
metadata:
  name: storage
  labels:
    app: storage
spec:
  selector:
    app: storage
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
  type: ClusterIP
