apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      automountServiceAccountToken: false
      containers:
        - name: user
          image: mjkundta/user:<TAG>
          command: ["node", "dist/apps/user/src/main"]
          resources:
            requests:
              memory: "800Mi"  
              cpu: "220m"     
            limits:
              memory: "800Mi" 
              cpu: "220m" 
          env:
            - name: NODE_ENV
              value: "production"
