export const FAMILY_PACKAGE_EXPIRED = 'FAMILY_PACKAGE_EXPIRED';
export const FAMILY_INFO_CHANGED = 'FAMILY_INFO_CHANGED';
export const FAMILY_MEMBER_ADDED = 'FAMILY_MEMBER_ADDED';
export const FAMILY_MEMBER_REMOVED = 'FAMILY_MEMBER_REMOVED';

export const CHAT_NEW_MESSAGE_FROM_USER = 'CHAT_NEW_MESSAGE_FROM_USER';
export const CHAT_NEW_MESSAGE_FROM_FAMILY = 'CHAT_NEW_MESSAGE_FROM_FAMILY';

export const CALENDAR_EVENT_CREATED = 'CALENDAR_EVENT_CREATED';
export const CALENDAR_EVENT_UPDATED = 'CALENDAR_EVENT_UPDATED';
export const CALENDAR_EVENT_DELETED = 'CALENDAR_EVENT_DELETED';
export const CALENDAR_EVENT_OCCURED_REPEATLY_DAILY =
  'CALENDAR_EVENT_OCCURED_REPEATLY_DAILY';
export const CALENDAR_EVENT_OCCURED_REPEATLY_WEEKLY =
  'CALENDAR_EVENT_OCCURED_REPEATLY_WEEKLY';
export const CALENDAR_EVENT_OCCURED_REPEATLY_MONTHLY =
  'CALENDAR_EVENT_OCCURED_REPEATLY_MONTHLY';
export const CALENDAR_EVENT_OCCURED_REPEATLY_YEARLY =
  'CALENDAR_EVENT_OCCURED_REPEATLY_YEARLY';
export const CALENDAR_EVENT_OCCURED_NON_REPEATLY =
  'CALENDAR_EVENT_OCCURED_NON_REPEATLY';

export const CHECKLIST_CREATED = 'CHECKLIST_CREATED';
export const CHECKLIST_UPDATED = 'CHECKLIST_UPDATED';
export const CHECKLIST_DELETED = 'CHECKLIST_DELETED';
export const CHECKLIST_OCCURED = 'CHECKLIST_OCCURED';

export const GUIDELINE_CREATED = 'GUIDELINE_CREATED';
export const GUIDELINE_UPDATED = 'GUIDELINE_UPDATED';
export const GUIDELINE_DELETED = 'GUIDELINE_DELETED';
export const GUIDELINE_MARK_SHARED = 'GUIDELINE_MARK_SHARED';

export const EDUCATION_CREATED = 'EDUCATION_CREATED';
export const EDUCATION_UPDATED = 'EDUCATION_UPDATED';
export const EDUCATION_DELETED = 'EDUCATION_DELETED';
export const EDUCATION_SUCCESS = 'EDUCATION_SUCCESS';

export const EXPENSE_REPORT = 'EXPENSE_REPORT';
export const INCOME_REPORT = 'INCOME_REPORT';
