export const PERMISSION_CALENDAR = 'Calendar';
export const PERMISSION_GUIDELINE = 'Guideline';
export const PERMISSION_EDUCATION = 'Education';
export const PERMISSION_FINANCE = 'Finance';
export const PERMISSION_SHOPPING = 'Shopping';
export const PERMISSION_HOUSEHOLD = 'Household';

export const PERMISSIONS = [
  PERMISSION_CALENDAR,
  PERMISSION_GUIDELINE,
  PERMISSION_EDUCATION,
  PERMISSION_FINANCE,
  PERMISSION_SHOPPING,
  PERMISSION_HOUSEHOLD,
];
