export const PERMISSION_CALENDAR = 'calendar';
export const PERMISSION_GUIDELINE = 'guideline';
export const PERMISSION_EDUCATION = 'education';
export const PERMISSION_FINANCE = 'finance';
export const PERMISSION_SHOPPING = 'shopping';
export const PERMISSION_INVOICE = 'invoice';
export const PERMISSION_HOUSEHOLD = 'household';

export const PERMISSIONS = [
  PERMISSION_CALENDAR,
  PERMISSION_GUIDELINE,
  PERMISSION_EDUCATION,
  PERMISSION_FINANCE,
  PERMISSION_SHOPPING,
  PERMISSION_INVOICE,
  PERMISSION_HOUSEHOLD,
];
